### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by liondani**
kenCode Greek translation is ready!

### CODE REVIEW

**Comment by kenCode-de** [comment]
Hmm, github is telling me that your xml file edit cannot be committed because it has conflicts. can you please refork or something and fix that so i can check it over and commit it? thanx in advance liondani :)

**Comment by kenCode-de** [comment]
Nope, same error, it says your xml file still has "conflicts that must be resolved" and cannot be committed.

**Comment by kenCode-de** [comment]
Nope, same error still. Sorry liondani, I wish I knew what to do, I am no github guru tho, that's for sure

**Comment by martykan** [comment]
I will merge it, just a moment.

**Comment by liondani** [comment]
please inform me about the error if merged successful with your edit/fix

**Comment by kenCode-de** [comment]
OK, @liondani how does it look now? 
https://github.com/kenCode-de/smartcoins-wallet/blob/master/app/src/main/res/values-el/strings.xml

**Pull request merged**
